apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  labels:
    app: udagram-api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: megop/udagram-api-feed:latest
        resources:
          requests:
            memory: "1500Mi"
            cpu: "500m"
          limits:
            memory: "2500Mi"
            cpu: "750m"
        ports:
        - containerPort: 80
        envFrom:
          - secretRef:
              name: aws-secret
          - secretRef:
              name: env-secret
          - configMapRef:
              name: env-config
