apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  labels:
    service: udagram-api-feed
spec:
  selector:
    matchLabels:
      service: udagram-api-feed
  replicas: 2
  template:
    metadata:
      labels:
        service: udagram-api-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: megop/udagram-api-feed:v1
        resources:
          requests:
            memory: "1500Mi"
            cpu: "500m"
          limits:
            memory: "2500Mi"
            cpu: "750m"
        envFrom:
          - secretRef:
              name: aws-secret
          - secretRef:
              name: env-secret
          - configMapRef:
              name: env-config
