apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverseproxy
  labels:
    app: udagram-reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-reverseproxy
  template:
    metadata:
      labels:
        app: udagram-reverseproxy
    spec:
      containers:
      - name: udagram-reverseproxy
        image: megop/udagram-reverseproxy:latest
        resources:
          requests:
            memory: "1000Mi"
          limits:
            memory: "2000Mi"
        ports:
        - containerPort: 8080
        envFrom:
          - secretRef:
              name: aws-secret
          - secretRef:
              name: env-secret
          - configMapRef:
              name: env-config
