version: 2.1

jobs:
  build:
    docker:
      - image: "cimg/node:14.15"
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - run:
          command: |
            docker login -u megop -p "$DOCKER_HUB_PASSWORD"
            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed megop/udagram-api-feed:latest
            docker push megop/udagram-api-feed:latest
            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user megop/udagram-api-user:latest
            docker push megop/udagram-api-user:latest
            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend megop/udagram-frontend:v1
            docker push megop/udagram-frontend:v1
            docker build -t udagram-reverseproxy ./udagram-reverseproxy
            docker tag udagram-reverseproxy megop/udagram-reverseproxy:latest
            docker push megop/udagram-reverseproxy:latest

workflows:
  udagram:
    jobs:
      - build
