version: 2.1

jobs:
  build:
    docker:
      - image: "cimg/node:14.15"
    steps:
      - checkout
      - run:
          command: |
            docker login -u megop -p "$DOCKER_HUB_PASSWORD"
            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed megop/udagram-api-feed:latest
            docker push megop/udagram-api-feed:latest
            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user megop/udagram-api-user:latest
            docker push megop/udagram-api-user:latest
            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend:local megop/udagram-frontend:latest
            docker push megop/udagram-frontend:latest
            docker build -t udagram-reverseproxy ./udagram-reverseproxy
            docker tag reverseproxy megop/reverseproxy:latest
            docker push megop/reverseproxy:latest

workflows:
  udagram:
    jobs:
      - build
