version: 2.1

jobs:
  build:
    docker:
      - image: "cimg/node:14.15"
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - run:
          command: |
            docker login -u megop -p "$DOCKER_HUB_PASSWORD"
            docker-compose -f docker-compose-build.yaml build --parallel
            docker tag udagram-api-feed megop/udagram-api-feed:v7
            docker push megop/udagram-api-feed:v7
            docker tag udagram-api-user megop/udagram-api-user:v7
            docker push megop/udagram-api-user:v7
            docker tag udagram-frontend megop/udagram-frontend:v7
            docker push megop/udagram-frontend:v7
            docker tag reverseproxy megop/reverseproxy:v7
            docker push megop/reverseproxy:v7
workflows:
  udagram:
    jobs:
      - build
