version: 2.1

jobs:
  build:
    docker:
    	auth:
    	  username: megop
          password: dckr_pat_NFhGPW0RVtjkcwuZbQ8UWu14eOo
      - run:
          name: docker compose
          command: docker-compose -f docker-compose-build.yaml build --parallel       
workflows:
  udagram:
    jobs:
      - build
      - hold:
          filters:
            branches:
              only:
                - master
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
