version: 2.1
orbs:
  docker: circleci/docker@1.7.0

jobs:
  build:
    docker:
    steps:
      - run:
          name: docker compose
          command: docker build -t udagram-api-feed ./udagram-api-feed

      #- auth:
         # username: megop
          #password: dckr_pat_NFhGPW0RVtjkcwuZbQ8UWu14eOo    
workflows:
  udagram:
    jobs:
      - build
      - hold:
          filters:
            branches:
              only:
                - master
          type: approval
          requires:
            - build
      #- deploy:
          #requires:
            #- hold
