version: 2.1
orbs:
  docker: circleci/docker@1.7.0

jobs:
  build:
    docker:
      # replace with your preferred image
      - image: "cimg/node:14.15"
    steps:
      - docker/install-docker-compose
      - checkout
      - run:
          name: docker compose
          command: docker-compose -f docker-compose-build.yaml build --parallel 

      #- auth:
         # username: megop
          #password: dckr_pat_NFhGPW0RVtjkcwuZbQ8UWu14eOo    
workflows:
  udagram:
    jobs:
      - build
      - hold:
          filters:
            branches:
              only:
                - master
          type: approval
          requires:
            - build
      #- deploy:
          #requires:
            #- hold
