version: 2.1

jobs:
  build:
    docker:    
      - checkout
      # Use root level package.json to install dependencies in the frontend app
      - run:
          name: docker compose
          command: |
            docker login -u megop -p dckr_pat_NFhGPW0RVtjkcwuZbQ8UWu14eOo
            docker-compose -f docker-compose-build.yaml build --parallel
  deploy:
      - checkout
      - run:
          name: Deploy App
          # TODO: Install, build, deploy in both apps
          command: |
            echo "# TODO: Install, build, deploy in both apps"
            
workflows:
  udagram:
    jobs:
      - build
      - hold:
          filters:
            branches:
              only:
                - master
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
